### ISSUE TITLE
The Browser Hangs after entering the username

### ISSUE THREAD

**Issue by bineetNaidu** [avazkhan2808/chat-app#3]
I was Lookin at your project at https://devchallenges.io/, it felt interesting so visited your project live demos.
And in this one the chat app , I encountered some bugs while proceeding to sign in with a user , unfortunately the browser starts to get hang not reponses.

**Comment by jcbbb** [comment]
@bineetNaidu It's one of the first projects I did in JavaScript, so it's very bad. I don't even know what's happening there. I just followed a tutorial and worked at the time, now apparently not working
